### ISSUE TITLE
Créa : Maquette du site

### ISSUE THREAD

**Issue by AmFlint** [AmFlint/Semaine-Intensive-Int-#3]
- [x] Rechercher des images
- [x] Rechercher du contenu (textes, citations)
- [x] Détourer les images needed
- [x] Chercher un code couleur
- [x] Faire la maquette de l'index du site (toutes les informations claires et visibles)
- [x] Faire la maquette des pages secondaires du site (Contact, Livraison, nos recettes etc)
- [x] design la maquette Livraison
- [x] Faire la maquette Contact
- [x] Faire la maquette A propos
- [ ] Faire la maquette Connexion

**Comment by aellanglet** [comment]
RIP la maquette connexion, qui s'en occupait ?
